### PR TITLE
Add Bootstrap caret on dropdown menu

### PR DESCRIPTION
**Pull request by zvineyard**

### CODE REVIEW

**Comment by Piterden** [comment]
Do you have a screenshot of a result?

Because for me that caret is invisible...

**Comment by zvineyard** [comment]
Yes--it will only show with Bootstrap installed/enabled. 

screen shot 2017-10-23 at 8 42 13 am

**Comment by Piterden** [comment]
Excuse me, but isn't it your theme related thing? I don't see something similar in Pyro backend.

You can extend or override any part, there is no need to make a PR. Or I understand something wrong?

**Comment by zvineyard** [comment]
The way it displays in my theme is the standard Bootstrap Navbar example: https://getbootstrap.com/docs/3.3/components/#navbar. Based purely on design, I don't think there would be an opportunity in the backend for this to display. Also, looking at the plugin, there doesn't seem to be an option that allows for an override that would include the caret.

**Comment by RyanThompson** [comment]
This is done with the `{% if options.get('dropdown_toggle') %}` option.

**Pull request closed without merging**
